# Generated by Django 6.0.5 on 2026-06-03 14:33

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTask',
            fields=[
                ('id', models.UUIDField(db_index=True, default=apps.accounts.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=50)),
                ('raw_payload', models.TextField()),
                ('error_message', models.TextField()),
                ('error_stacktrace', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failed_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'failed_task',
                'verbose_name_plural': 'failed_tasks',
                'db_table': 'failed_tasks',
            },
        ),
    ]
