# Generated by Django 5.x on 2026-05-29
import apps.accounts.models
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTask',
            fields=[
                ('id', models.UUIDField(db_index=True, default=apps.accounts.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=50)),
                ('raw_payload', models.TextField()),
                ('error_message', models.TextField()),
                ('error_stacktrace', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failed_tasks', to='accounts.user')),
            ],
            options={
                'verbose_name': 'failed_task',
                'verbose_name_plural': 'failed_tasks',
                'db_table': 'failed_tasks',
            },
        ),
    ]
