# Generated by Django 6.0.6 on 2026-06-09 06:00

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncTask',
            fields=[
                ('job_id', models.UUIDField(db_index=True, default=apps.accounts.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('result_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'async_task',
                'verbose_name_plural': 'async_tasks',
                'db_table': 'async_tasks',
            },
        ),
    ]
