# Generated by Django 6.0.5 on 2026-05-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpushsubscription',
            name='endpoint',
            field=models.URLField(max_length=2000),
        ),
        migrations.AddConstraint(
            model_name='userpushsubscription',
            constraint=models.UniqueConstraint(fields=('user', 'endpoint'), name='unique_user_push_subscription'),
        ),
    ]
