# Generated by Django 6.0.6 on 2026-06-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpushsubscription',
            name='device_hint',
            field=models.CharField(blank=True, choices=[('FCM', 'Firebase Cloud Messaging'), ('APPLE', 'Apple Web Push'), ('GENERIC', 'Generic Web Push')], default='GENERIC', max_length=20),
        ),
        migrations.AddField(
            model_name='userpushsubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
