# Generated by Django 5.x on 2026-05-29
import apps.accounts.models
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantTemplate',
            fields=[
                ('id', models.UUIDField(db_index=True, default=apps.accounts.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('vendor_registration_number', models.CharField(max_length=10, unique=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('parsing_rules', models.JSONField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'merchant_template',
                'verbose_name_plural': 'merchant_templates',
                'db_table': 'merchant_templates',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.UUIDField(db_index=True, default=apps.accounts.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('vendor_registration_number', models.CharField(default='0000000000', max_length=10)),
                ('vendor_name', models.CharField(max_length=255)),
                ('transaction_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supply_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('raw_llm_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='accounts.user')),
            ],
            options={
                'verbose_name': 'ledger',
                'verbose_name_plural': 'ledgers',
                'db_table': 'ledgers',
            },
        ),
        migrations.CreateModel(
            name='LedgerItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=apps.accounts.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ledgers.ledger')),
            ],
            options={
                'verbose_name': 'ledger_item',
                'verbose_name_plural': 'ledger_items',
                'db_table': 'ledger_items',
            },
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(fields=('user', 'vendor_registration_number', 'transaction_date', 'total_amount'), name='unique_user_vendor_date_amount'),
        ),
    ]
