# Generated by Django 6.0.5 on 2026-06-03 14:33

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantTemplate',
            fields=[
                ('id', models.UUIDField(db_index=True, default=apps.accounts.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('vendor_registration_number', models.CharField(max_length=10, unique=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('parsing_rules', models.JSONField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'merchant_template',
                'verbose_name_plural': 'merchant_templates',
                'db_table': 'merchant_templates',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.UUIDField(db_index=True, default=apps.accounts.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('vendor_registration_number', models.CharField(default='0000000000', max_length=10)),
                ('vendor_name', models.CharField(max_length=255)),
                ('transaction_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supply_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('raw_llm_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ledger',
                'verbose_name_plural': 'ledgers',
                'db_table': 'ledgers',
            },
        ),
        migrations.CreateModel(
            name='LedgerItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=apps.accounts.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ledgers.ledger')),
            ],
            options={
                'verbose_name': 'ledger_item',
                'verbose_name_plural': 'ledger_items',
                'db_table': 'ledger_items',
            },
        ),
        migrations.CreateModel(
            name='ReceiptUploadJob',
            fields=[
                ('id', models.UUIDField(db_index=True, default=apps.accounts.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('raw_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_job', to='ledgers.ledger')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'receipt_upload_job',
                'verbose_name_plural': 'receipt_upload_jobs',
                'db_table': 'receipt_upload_jobs',
            },
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(fields=('user', 'vendor_registration_number', 'transaction_date', 'total_amount'), name='unique_ledger_transaction'),
        ),
    ]
