# Generated by Django 6.0.5 on 2026-06-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='category',
            field=models.CharField(db_index=True, default='미분류', max_length=100),
        ),
    ]
