# Generated by Django 6.0.5 on 2026-05-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userpushsubscription_endpoint_and_more'),
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ledger',
            name='unique_user_vendor_date_amount',
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(fields=('user', 'vendor_registration_number', 'transaction_date', 'total_amount'), name='unique_ledger_transaction'),
        ),
    ]
