# Generated by Django 6.0.5 on 2026-06-02 22:54

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0002_remove_ledger_unique_user_vendor_date_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptUploadJob',
            fields=[
                ('id', models.UUIDField(db_index=True, default=apps.accounts.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'receipt_upload_job',
                'verbose_name_plural': 'receipt_upload_jobs',
                'db_table': 'receipt_upload_jobs',
            },
        ),
    ]
