# Generated by Django 6.0.5 on 2026-06-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0002_ledger_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptuploadjob',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
