# Generated by Django 6.0.6 on 2026-06-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0003_receiptuploadjob_failure_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='approval_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='transaction_date',
            field=models.DateTimeField(),
        ),
    ]
