# Generated by Django 6.0.5 on 2026-06-02 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userpushsubscription_endpoint_and_more'),
        ('ledgers', '0003_receiptuploadjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptuploadjob',
            name='ledger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_job', to='ledgers.ledger'),
        ),
        migrations.AddField(
            model_name='receiptuploadjob',
            name='raw_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiptuploadjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_jobs', to='accounts.user'),
        ),
    ]
