# Generated by Django 6.0.6 on 2026-06-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0005_alter_ledger_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_date',
            field=models.DateTimeField(),
        ),
    ]
