# Generated by Django 6.0.6 on 2026-06-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0006_alter_ledger_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchanttemplate',
            name='is_auto_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchanttemplate',
            name='regex_error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
