# Generated by Django 6.0.6 on 2026-06-13 06:09

import apps.accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0007_merchanttemplate_is_auto_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchanttemplate',
            name='consistency_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='merchanttemplate',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchanttemplate',
            name='last_healing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchanttemplate',
            name='self_healing_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TemplateExecutionHistory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=apps.accounts.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('execution_time', models.DateTimeField(auto_now_add=True)),
                ('parsing_mode', models.CharField(max_length=10)),
                ('is_success', models.BooleanField(default=True)),
                ('user_corrected', models.BooleanField(default=False)),
                ('corrected_diff', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_histories', to='ledgers.ledger')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_histories', to='ledgers.merchanttemplate')),
            ],
            options={
                'verbose_name': 'template_execution_history',
                'verbose_name_plural': 'template_execution_histories',
                'db_table': 'template_execution_histories',
            },
        ),
    ]
