# Generated by Django 6.0.6 on 2026-06-13 18:35

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0008_merchanttemplate_consistency_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.UUIDField(db_index=True, default=apps.accounts.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('budget_month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=0, default=1000000, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'monthly_budget',
                'verbose_name_plural': 'monthly_budgets',
                'db_table': 'monthly_budgets',
                'constraints': [models.UniqueConstraint(fields=('user', 'budget_month'), name='unique_user_budget_month')],
            },
        ),
    ]
