# Generated by Django 6.0.6 on 2026-06-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0010_ledger_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ledger',
            name='ledger_user_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='ledger',
            name='ledger_vendor_trgm_idx',
        ),
        migrations.AddField(
            model_name='ledger',
            name='ignore_duplicate_check',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='ledger',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='raw_text_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
