# Generated by Django 6.0.6 on 2026-06-16 15:08

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0011_remove_ledger_ledger_user_date_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptTask',
            fields=[
                ('id', models.UUIDField(db_index=True, default=apps.accounts.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('parser_stage', models.CharField(choices=[('OLLAMA', 'Ollama'), ('GEMINI_TEXT', 'Gemini Text'), ('GEMINI_VISION', 'Gemini Vision'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_tasks', to='ledgers.ledger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'receipt_task',
                'verbose_name_plural': 'receipt_tasks',
                'db_table': 'receipt_tasks',
            },
        ),
    ]
