# Generated by Django 6.0.6 on 2026-06-20 15:34

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_userpushsubscription_device_hint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTask',
            fields=[
                ('id', models.UUIDField(db_index=True, default=apps.accounts.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('RECEIPT_PROCESSED', '영수증 처리 완료'), ('BUDGET_THRESHOLD_ALERT', '월별 예산 임계 초과')], max_length=50)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('action_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', '대기 중'), ('PROCESSING', '처리 중'), ('SUCCESS', '성공'), ('FAILED', '실패')], default='PENDING', max_length=20)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_tasks', to='accounts.userpushsubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_tasks',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=apps.accounts.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('FCM', 'Firebase Cloud Messaging'), ('APPLE_VAPID', 'Apple Web Push (VAPID)'), ('GENERIC_VAPID', 'Generic Web Push (VAPID)')], max_length=20)),
                ('endpoint_hint', models.CharField(max_length=255)),
                ('http_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, max_length=2000, null=True)),
                ('is_success', models.BooleanField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notificationtask')),
            ],
            options={
                'db_table': 'notification_logs',
            },
        ),
        migrations.AddIndex(
            model_name='notificationtask',
            index=models.Index(fields=['user', 'status', 'created_at'], name='notificatio_user_id_c849d6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtask',
            index=models.Index(fields=['idempotency_key'], name='notificatio_idempot_ac0246_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationtask',
            constraint=models.UniqueConstraint(fields=('idempotency_key', 'subscription'), name='unique_notification_task_idempotency'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', 'is_success', 'created_at'], name='notificatio_user_id_f18597_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['created_at'], name='notificatio_created_45a1e0_idx'),
        ),
    ]
