# Generated by Django 6.0.6 on 2026-06-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기 중'), ('SENT', '발송 완료'), ('DELIVERED', '수신 완료'), ('FAILED', '실패')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
